export {default as DropDownA} from './Home1/DropDownA'
export {default as DropDownB} from './Home1/DropDownB'
export {default as DropDownC} from './Home1/DropDownC'
export {default as Cart} from './Home1/Cart'
export {default as HomeHero} from './Home1/HomeHero'
export {default as Clients} from './Home1/Clients'
export {default as AboutSection} from './Home1/AboutSection'
export {default as Header} from './Career/Header'
export {default as CareerClients} from './Career/Clients'
export {default as Benefits} from './Career/Benefits'
export {default as Careers} from './Career/Careers'
export {default as Getintouch} from './shared/components/Getintouch'
export {default as TeamHero} from './Leadership/Hero'
export {default as TeamCards} from './Leadership/TeamCards'
export {default as Video} from './Leadership/Video'
export {default as Faq} from './Leadership/Faq'
export {default as Services} from './Home1/Services'
export {default as Itservices} from './Home1/Itservices'
export {default as Git} from './Home1/Git'
export {default as Project} from './Home1/Project'
export {default as Testimonials} from './Home1/Testimonials'
export {default as Slider} from './Home1/Slider'
export {default as TestimonialCard} from './Home1/TestimonialCard'
export {default as Build} from './Home1/Build'
export {default as GetHero} from './Getaquote/Hero'
export {default as Form} from './Getaquote/Form'
export {default as Countrys} from './Getaquote/Countrys'
export { default as Projects } from "./Home3/Projects";
export { default as OurServices } from "./Home3/OurServices";
export { default as Deliver } from "./Home3/Deliver";
export {default as ButtonLink} from './shared/components/ButtonLink'
export {default as Navbar} from './shared/layout/Navbar'
